name: Jest Test

on: workflow_dispatch

jobs:
  prepare-yarn-cache:
    name: Prepare yarn cache
    strategy:
      fail-fast: false
      matrix:
        # for some reason the Windows cache doesn't work
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - name: Validate cache
        env:
          # Use PnP and disable postinstall scripts as this just needs to
          # populate the cache for the other jobs
          YARN_NODE_LINKER: pnp
          YARN_ENABLE_SCRIPTS: false
        run: yarn --immutable

  typecheck:
    name: Running TypeScript compiler
    runs-on: ubuntu-latest
    needs: prepare-yarn-cache

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: install
        run: yarn --immutable
      - name: build
        run: yarn build
      - name: test typings
        run: yarn test-types
      - name: verify TypeScript@4.3 compatibility
        run: yarn verify-old-ts
        
  lint:
    name: Running Lint
    runs-on: ubuntu-latest
    needs: prepare-yarn-cache

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: install
        run: yarn --immutable
      - name: build
        run: yarn build:js
      - name: verify Yarn PnP compatibility
        run: yarn verify-pnp
      - name: run eslint
        run: yarn lint
      - name: run prettier
        run: yarn lint:prettier:ci
      - name: check copyright headers
        run: yarn check-copyright-headers

  yarn-validate:
    name: Validate Yarn dependencies and constraints
    runs-on: ubuntu-latest
    needs: prepare-yarn-cache
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: 'Check for unmet constraints (fix w/ "yarn constraints --fix")'
        run: yarn constraints
      - name: 'Check for duplicate dependencies (fix w/ "yarn dedupe")'
        run: yarn dedupe --check
